name: Process Events

on:
  workflow_dispatch:

jobs:
  generate-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate events
        id: get-events
        run: |
          events=$(python3 ./scripts/prepare-all-events.py)
          echo "events=$events" >> $GITHUB_OUTPUT
    outputs:
      events: ${{ steps.get-events.outputs.events }}

  process-events:
    needs: generate-events
    runs-on: ubuntu-latest
    strategy:
      matrix:
        event: ${{ fromJson(needs.generate-events.outputs.events) }}
      max-parallel: 4
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Process event
        run: |
          echo "Processing event: ${{ matrix.event }}"
          python3 ./scripts/process-one-event.py '${{ matrix.event }}'
