name: Process Events

on:
  workflow_dispatch:

jobs:
  generate-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate events
        id: get-events
        run: |
          events=$(python3 scripts/prepare-all-events.py)
          echo ---------
          echo Events = $events
          echo ---------
          echo "events=$events" >> $GITHUB_OUTPUT
    outputs:
      events: ${{ steps.get-events.outputs.events }}

  process-events:
    needs: generate-events
    runs-on: ubuntu-latest
    strategy:
      matrix:
        event: ${{ fromJson(needs.generate-events.outputs.events) }}
      max-parallel: 4
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Process event
        run: |
          echo "Processing event: ${{ toJson(matrix.event) }}"
          python3 scripts/process-one-event.py 'MY_ACTION' '${{ toJson(matrix.event) }}'

  final-check:
    needs: process-events
    runs-on: ubuntu-latest
    steps:
      - name: Check for failures
        run: |
          if [[ "${{ job.status }}" == "failure" ]]; then
            echo "Some events failed to process."
            exit 1
          else
            echo "All events processed successfully."
          fi
