name: Process Events

on:
  workflow_dispatch:

jobs:
  generate-events:
    runs-on: ubuntu-latest
    outputs:
      events: ${{ steps.get-events.outputs.events }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate events
        id: get-events
        run: |
          events=$(python3 scripts/prepare-all-events.py)
          echo ---------
          echo Events = $events
          echo ---------
          echo "events=$events" >> $GITHUB_OUTPUT

  process-events:
    needs: generate-events
    runs-on: ubuntu-latest
    strategy:
      matrix:
        event: ${{ fromJson(needs.generate-events.outputs.events) }}
      max-parallel: 4
    continue-on-error: true
    outputs:
      status: ${{ steps.check-status.outputs.has_failure }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Process event
        id: check-status
        run: |
          echo "Processing event: ${{ toJson(matrix.event) }}"
          python3 scripts/process-one-event.py 'MY_ACTION' '${{ toJson(matrix.event) }}'
          echo "Processing done. ========"
          if [ $? -ne 0 ]; then
            echo "script2.py failed for event: ${{ toJson(matrix.event) }}"
            echo "has_failure=yes" >> $GITHUB_OUTPUT
          else
            echo "script2.py succeeded for event: ${{ toJson(matrix.event) }}"
          fi

  final-check:
    needs: process-events
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate job statuses
        id: aggregate-statuses
        run: |
          echo HAS_FAILURE = ${{ needs.process-events.outputs.has_failure }}
